name: Cypress E2E & component on Chrome

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        env: REACT_APP_SERVICE_ACCOUNT: ${{ secrets.REACT_APP_SERVICE_ACCOUNT }}
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"

      - name: Run Component Testing
        uses: cypress-io/github-action@v3
        with:
          install: false
          component: true
          browser: chrome
          wait-on: "http://localhost:3000"